# Generated by Django 2.1.3 on 2018-12-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.IntegerField(max_length=10)),
                ('field_2', models.IntegerField(max_length=10)),
                ('field_3', models.IntegerField(max_length=10)),
                ('field_4', models.IntegerField(max_length=10)),
                ('field_5', models.IntegerField(max_length=10)),
                ('field_6', models.IntegerField(max_length=10)),
                ('field_7', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='feeling',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image2songs.UserData'),
        ),
    ]
