# Generated by Django 2.1.3 on 2018-12-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image2songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='field_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='field_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='field_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='field_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='field_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='field_6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='field_7',
            field=models.IntegerField(),
        ),
    ]
