# Generated by Django 2.1.3 on 2018-12-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image2songs', '0002_auto_20181202_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeling',
            old_name='field_1',
            new_name='anger',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='field_2',
            new_name='disgust',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='score',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='field_3',
            new_name='fear',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='field_4',
            new_name='happiness',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='field_5',
            new_name='neutral',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='field_6',
            new_name='sadness',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='field_7',
            new_name='surprise',
        ),
        migrations.AddField(
            model_name='userdata',
            name='token_s',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
