# Generated by Django 2.1.5 on 2019-02-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image2songs', '0003_auto_20181203_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='email',
        ),
        migrations.AddField(
            model_name='feeling',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
