# Generated by Django 2.1.5 on 2019-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image2songs', '0004_auto_20190203_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='datetime',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
